data:
  raw: Data/raw/  
  processed: Data/processed
  preprocessed: "Data/processed/data_segments_all_channels_combined_2_5secondepoch.npz" # Combined preprocessed data from all subjects
  fs: 128  # From paper https://github.com/vlawhern/arl-eegmodels/blob/master/EEGModels.py
  epoch_length: 2.5 # Length of each epoch in seconds


label_maps:
  0_vs_2: {0: 0, 1: null, 2: 1}
  0_vs_1: {0: 0, 1: 1, 2: null}
  1_vs_2: {0: null, 1: 0, 2: 1}
  0_vs_1and2: {0: 0, 1: 1, 2: 1}
  0and1_vs_2: {0: 0, 1: 0, 2: 1}


  